### ISSUE TITLE
plasma-phone-settings doesn't ship kdeglobals

### ISSUE THREAD

**Issue by bhush9** [debian-pm/halium-debian-repo#2]
https://github.com/plasma-phone-packaging/plasma-phone-settings-packaging/tree/kubuntu_unstable/debian

**Comment by jbruechert** [comment]
It seems like my repository is based on the master branch instead of kubuntu_unstable. I'll rebase it on your kubuntu_unstable branch.

**Comment by bhush9** [comment]
While at it please also ship kdeglobals.armhf for i386 platform to make @IlyaBizyaev happy and fixing scaling issues for him as well

**Comment by jbruechert** [comment]
I pushed a new build to the repository. Is the issue fixed after upgrading?

**Comment by IlyaBizyaev** [comment]
Thank you, this fixes half of the scaling issue for me :)
![img_20180325_152112](https://user-images.githubusercontent.com/11175213/37874967-43f36ce2-3041-11e8-891e-0ceedce22ee6.jpg)
![img_20180325_152133](https://user-images.githubusercontent.com/11175213/37874963-3e83e700-3041-11e8-9b72-2a80f8c5a51f.jpg)
![img_20180325_152207](https://user-images.githubusercontent.com/11175213/37874966-416fbc82-3041-11e8-9c36-021d7305cc42.jpg)

**Comment by bhush9** [comment]
Fixed my issue, closing this now here.
