### ISSUE TITLE
provide qtvirtualkeyboard-opensource-src temporary

### ISSUE THREAD

**Issue by bhush9** [debian-pm/halium-debian-repo#3]
this is rather workaround, but... debian have tests failing which prevents publish of qtvirtualkeyboard on buster

https://buildd.debian.org/status/fetch.php?pkg=qtvirtualkeyboard-opensource-src&arch=armhf&ver=5.9.2%2Bdfsg-1&stamp=1509141977&raw=0

And that makes no virtualkeyboard in Plasma mobile.. issue is fixed upstream in https://salsa.debian.org/qt-kde-team/qt/qtvirtualkeyboard/commit/3fd6449ff66461cf6a483d61912079ecdc0405b2

However it seems it will take while before 5.10.x rolls out in testing.. meanwhile can you provide qtvirtualkeyboard for armhf binaries?

Thanks

**Comment by jbruechert** [comment]
A build is in progress :)

**Comment by jbruechert** [comment]
Fixed in ee306159f4c29e9854b58e43d4dde3b06280feb7
