### ISSUE TITLE
Build ofono qml binding and telepathy-ofono

### ISSUE THREAD

**Issue by bhush9** [debian-pm/halium-debian-repo#6]
https://packages.ubuntu.com/source/xenial/telepathy-ofono
https://packages.ubuntu.com/source/bionic/libqofono

**Comment by jbruechert** [comment]
Added a libqofono built in cc5202e50dcb6e6fc5460c8ee08e68077ed38cb8

**Comment by jbruechert** [comment]
I added telepathy-ofono and it's dependency ofono-qt in bfed2403a55b053421a791272ff451719ddc61d6. Please test if the packages are working as expected and close this if it's the case :)

**Comment by bhush9** [comment]
Works as expected, thanks! \o/

(though this is with local build of ofono, see #7 for more details)
